<template>
  <AppHeader />
  <router-view />
  <trendingProducts />
  <sellProductList />
  <AppFooter />
</template>

<script>
import AppHeader from "@/components/AppHeader.vue";
import AppFooter from "@/components/AppFooter.vue";
import trendingProducts from "@/components/trendingProducts.vue";
import sellProductList from "@/components/sellProductList.vue";

export default {
  name: "App",
  components: {
    AppHeader,
    AppFooter,
    trendingProducts,
    sellProductList,
  },
  data() {
    return {
      /* 
      categories: [
    {
      id: 1,
      name: "imageAndSound",
      text: "Image & Sound",
      alt: "Image & Sound",
      img: require("@/assets/imageSound.png"),
    },
    {
      id: 2,
      name: "ComputersAndTablets",
      text: "Computers & Tablets",
      alt: "Computers & Tablets",
      img: require("@/assets/computer.png"),
    },
    {
      id: 3,
      name: "HouseHoldAndLiving",
      text: "HouseHold & Living",
      alt: "HouseHold & Living",
      img: require("@/assets/houseHold.png"),
    },
    {
      id: 4,
      name: "AppKitchen",
      text: "kitchen",
      alt: "kitchen",
      img: require("@/assets/kitchen.png"),
    },
    {
      id: 5,
      name: "SportAndcare",
      text: "Sport & care",
      alt: "Sport & care",
      img: require("@/assets/sportsAndCare.png"),
    },
    {
      id: 6,
      name: "AllCategories",
      text: "All Categories",
      alt: "All Categories",
      img: require("@/assets/allCategories.png"),
    },
  ],
subCategories: [
    {
      sid: 1,
      categoryId: 1,
      name: "television",
      img: require("@/assets/imageAndSound/television.jpeg"),
    },
    {
      sid: 2,
      categoryId: 1,
      name: "television Accessories",
      img: require("@/assets/imageAndSound/accessories.jpeg"),
    },
    {
      sid: 3,
      categoryId: 1,
      name: "home Cinema",
      img: require("@/assets/imageAndSound/homeCinema.jpeg"),
    },
    {
      sid: 4,
      categoryId: 1,
      name: "speakers",
      img: require("@/assets/imageAndSound/speakers.png"),
    },
    {
      sid: 5,
      categoryId: 1,
      name: "hifi & personal audio",
      img: require("@/assets/imageAndSound/speakers.png"),
    },
    {
      sid: 6,
      categoryId: 2,
      name: "laptop",
      img: require("@/assets/computers/laptop.jpeg"),
    },
    {
      sid: 7,
      categoryId: 2,
      name: "tablets",
      img: require("@/assets/computers/tablets.jpeg"),
    },
    {
      sid: 8,
      categoryId: 2,
      name: "Ereaders",
      img: require("@/assets/computers/Ereaders.jpeg"),
    },
    {
      sid: 9,
      categoryId: 2,
      name: "desktop",
      img: require("@/assets/computers/desktop.jpeg"),
    },
    {
      sid: 10,
      categoryId: 2,
      name: "printers",
      img: require("@/assets/computers/printers.jpeg"),
    },
    {
      sid: 11,
      categoryId: 2,
      name: "networks & routers",
      img: require("@/assets/computers/routers.jpeg"),
    },
    {
      sid: 12,
      categoryId: 2,
      name: "peripherals",
      img: require("@/assets/computers/peripherals.jpeg"),
    },
    {
      sid: 13,
      categoryId: 2,
      name: "storage & memory",
      img: require("@/assets/computers/storage.jpeg"),
    },
    {
      sid: 14,
      categoryId: 3,
      name: "washing machine",
      img: require("@/assets/household/washingmachine.jpeg"),
    },
    {
      sid: 15,
      categoryId: 3,
      name: "clothes dryer",
      img: require("@/assets/household/clothdryer.jpeg"),
    },
    {
      sid: 16,
      categoryId: 3,
      name: "vaccum cleaners",
      img: require("@/assets/household/vaccumcleaner.jpeg"),
    },
    {
      sid: 17,
      categoryId: 3,
      name: "irons",
      img: require("@/assets/household/iron.jpeg"),
    },
    {
      sid: 18,
      categoryId: 3,
      name: "smart homes",
      img: require("@/assets/household/smarthome.jpeg"),
    },
    {
      sid: 19,
      categoryId: 3,
      name: "safety",
      img: require("@/assets/household/safety.jpeg"),
    },
    {
      sid: 20,
      categoryId: 3,
      name: "climate control",
      img: require("@/assets/household/klimaatbeheersing.jpg"),
    },
    {
      sid: 21,
      categoryId: 4,
      name: "refrigerators",
      img: require("@/assets/kitchen/koelkasten.jpg"),
    },
    {
      sid: 22,
      categoryId: 4,
      name: "Freezers",
      img: require("@/assets/kitchen/vriezers.jpg"),
    },
    {
      sid: 23,
      categoryId: 4,
      name: "Coffee",
      img: require("@/assets/kitchen/JuraZ10.jpg"),
    },
    {
      sid: 24,
      categoryId: 4,
      name: "Microwaves & Ovens",
      img: require("@/assets/kitchen/magnetrons.jpg"),
    },
    {
      sid: 25,
      categoryId: 4,
      name: "Hobs & Cookers",
      img: require("@/assets/kitchen/kookplaten.jpg"),
    },
    {
      sid: 26,
      categoryId: 4,
      name: "Kitchen machines & mixers",
      img: require("@/assets/kitchen/keukenmachine.jpg"),
    },
    {
      sid: 27,
      categoryId: 4,
      name: "Juices & Drinks",
      img: require("@/assets/kitchen/sappen.jpg"),
    },
    {
      sid: 28,
      categoryId: 4,
      name: "Deep frying",
      img: require("@/assets/kitchen/frituren.jpg"),
    },
    {
      sid: 29,
      categoryId: 4,
      name: "Waffle Irons & Gourmets",
      img: require("@/assets/kitchen/funcooking.jpg"),
    },
    {
      sid: 30,
      categoryId: 4,
      name: "Kitchen appliances",
      img: require("@/assets/kitchen/keukenapparaten.jpg"),
    },
    {
      sid: 31,
      categoryId: 4,
      name: "Kitchenware",
      img: require("@/assets/kitchen/keukengerei.jpg"),
    },
    {
      sid: 32,
      categoryId: 4,
      name: "Cooker hoods",
      img: require("@/assets/kitchen/afzuigkappen.jpg"),
    },
    {
      sid: 33,
      categoryId: 5,
      name: "Shave",
      img: require("@/assets/imageSound.png"),
    },
    {
      sid: 34,
      categoryId: 5,
      name: "Hair removal",
      img: require("@/assets/imageSound.png"),
    },
    {
      sid: 35,
      categoryId: 5,
      name: "Hair care",
      img: require("@/assets/imageSound.png"),
    },
    {
      sid: 36,
      categoryId: 5,
      name: "Oral care",
      img: require("@/assets/imageSound.png"),
    },
    {
      sid: 37,
      categoryId: 5,
      name: "Health",
      img: require("@/assets/imageSound.png"),
    },
    {
      sid: 38,
      categoryId: 5,
      name: "smartwatch",
      img: require("@/assets/imageSound.png"),
    },
    {
      sid: 39,
      categoryId: 5,
      name: "Baby stuff",
      img: require("@/assets/imageSound.png"),
    },
  ],
  subCategoriesItems: [
    {
      sid: 1,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "10000",
      rating: "4.4",
      description: "television description",
    },
    {
      sid: 1,
      sitem: 2,
      img: require("@/assets/subcategories/televisies.png"),
      price: "10000",
      rating: "4.4",
      description: "television description",
    },
    {
      sid: 2,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "20000",
      rating: "3.5",
      description: "description",
    },

    {
      sid: 3,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "10000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 4,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "10000",
      rating: "4.0",
      description: "description",
    },
    {
      sid: 5,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "1000",
      rating: "3.4",
      description: "description",
    },
    {
      sid: 6,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 7,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 8,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 9,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 10,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 11,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 12,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 13,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 14,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 15,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 16,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 17,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 18,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 19,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 20,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 21,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 22,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 23,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 24,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 25,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 26,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 27,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 28,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 29,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 30,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 31,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 32,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 33,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 34,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 35,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 36,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 37,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 38,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
    {
      sid: 39,
      sitem: 1,
      img: require("@/assets/subcategories/televisies.png"),
      price: "19000",
      rating: "3.6",
      description: "description",
    },
  ],
      */
      productCart: {
        total: null,
        userId: null,
        cartDetails: [
          {
            productId: null,
            productName: null,
            price: null,
            quantity: null,
          },
        ],
      },
    };
  },
  //     productCart: [
  //       {
  //         userId: null,
  //         productId: null,
  //         productName: null,
  //         price: null,
  //         quantity: null,
  //       },
  //     ],
  // };
  // },
  // created() {
  // localStorage.setItem("productCart", JSON.stringify(this.productCart));
  //   localStorage.setItem("categories", JSON.stringify(this.categories));
  //   localStorage.setItem("subCategories", JSON.stringify(this.subCategories));
  //   localStorage.setItem(
  //     "subCategoriesItems",
  //     JSON.stringify(this.subCategoriesItems)
  //   );
  // },
};
</script>
